//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IDemo02_FormData
{
	formNo: string;
	formTitle: string;
	expectDate: string;
	updDtm?: string;
	fieldA: string;
	fieldB: string;
	fieldC: string;
}
