//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IDemoBiz_UploadDetail
{
	unitName: string;
	amount1: number;
	amount2: number;
	amount3: number;
	amount4: number;
	amount5: number;
}
