//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IWeatherForecast
{
	date: string;
	temperatureC: number;
	temperatureF: number;
	summary: string;
}
export interface IMyTestDto
{
	testDateTime: string;
	testString: string;
	testDecimal: number;
	testBool: boolean;
}
