@N8ReactAppTpl.Server_HostAddress = http://localhost:5062

### WebAPI 測試 
GET {{N8ReactAppTpl.Server_HostAddress}}/api/weatherforecast/
Accept: application/json

### 健康測試
GET {{N8ReactAppTpl.Server_HostAddress}}/healthz
Accept: application/json

### 登入測試
POST {{N8ReactAppTpl.Server_HostAddress}}/api/account/login
Content-Type: application/json

{
  "userId": "smart",
  "credential": "foo",
  "vcode": "123456",
  "returnUrl": "/"
}


### Fil Handling 200 - 成功
POST {{N8ReactAppTpl.Server_HostAddress}}/api/Demo05/FailHandlingLab/200

### Fil Handling 400
POST {{N8ReactAppTpl.Server_HostAddress}}/api/Demo05/FailHandlingLab/204
